# Generated by Django 3.0.6 on 2020-05-09 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoboard', '0002_shared_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
